image: docker:20

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo $DOCKER_HOST
    - echo $DOCKER_DRIVER
    - >
      docker build
      --target code_base
      --tag laravel-app
      .
